package org.grimmory.epub4j.epub;

import static org.junit.jupiter.api.Assertions.fail;

import com.adobe.epubcheck.api.EpubCheck;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import org.grimmory.epub4j.domain.Author;
import org.grimmory.epub4j.domain.Book;
import org.grimmory.epub4j.domain.Identifier;
import org.grimmory.epub4j.domain.Resource;
import org.junit.jupiter.api.Test;

/** Validates that EPUBs generated by epub4j pass w3c/epubcheck validation. */
public class EpubCheckValidationTest {

  @Test
  public void testGeneratedEpubPassesEpubCheck() throws IOException {
    Book book = createTestBook();
    byte[] epubData = writeBookToByteArray(book);
    assertEpubValid(epubData, "testbook");
  }

  @Test
  public void testMinimalBookPassesEpubCheck() throws IOException {
    Book book = new Book();
    book.getMetadata().addTitle("Minimal Test Book");
    book.getMetadata().addAuthor(new Author("Test", "Author"));
    book.getMetadata()
        .addIdentifier(
            new Identifier(
                Identifier.Scheme.UUID, "urn:uuid:12345678-1234-1234-1234-123456789012"));

    try (InputStream chapterStream = requireResourceStream("/book1/chapter1.html");
        InputStream cssStream = requireResourceStream("/book1/book1.css")) {
      book.addSection("Chapter 1", new Resource(chapterStream, "chapter1.html"));
      book.addResource(new Resource(cssStream, "book1.css"));
    }

    byte[] epubData = writeBookToByteArray(book);
    assertEpubValid(epubData, "minimal");
  }

  private static void assertEpubValid(byte[] epubData, String name) throws IOException {
    Path tempFile = Files.createTempFile(name, ".epub");
    try {
      Files.write(tempFile, epubData);

      StringWriter sw = new StringWriter();
      PrintWriter pw = new PrintWriter(sw);
      EpubCheck epubCheck = new EpubCheck(tempFile.toFile(), pw);
      int result = epubCheck.doValidate();

      if (result != 0) {
        fail("EPUBCheck validation failed for " + name + ".epub:\n" + sw);
      }
    } finally {
      Files.deleteIfExists(tempFile);
    }
  }

  private Book createTestBook() throws IOException {
    Book book = new Book();
    book.getMetadata().addTitle("EPUB4J Validation Test Book");
    book.getMetadata().addIdentifier(new Identifier(Identifier.Scheme.ISBN, "987654321"));
    book.getMetadata().addAuthor(new Author("Joe", "Tester"));
    book.setCoverPage(loadResource("/book1/cover.html", "cover.html"));
    book.setCoverImage(loadResource("/book1/cover.png", "cover.png"));
    book.addSection("Chapter 1", loadResource("/book1/chapter1.html", "chapter1.html"));
    book.addResource(loadResource("/book1/book1.css", "book1.css"));
    book.addSection("Second chapter", loadResource("/book1/chapter2.html", "chapter2.html"));
    book.addResource(loadResource("/book1/flowers.jpg", "flowers.jpg"));
    book.addSection("Chapter 3", loadResource("/book1/chapter3.html", "chapter3.html"));
    return book;
  }

  private Resource loadResource(String path, String href) throws IOException {
    try (InputStream is = requireResourceStream(path)) {
      return new Resource(is, href);
    }
  }

  private InputStream requireResourceStream(String path) {
    InputStream is = getClass().getResourceAsStream(path);
    if (is == null) {
      throw new IllegalStateException("Missing test resource on classpath: " + path);
    }
    return is;
  }

  private static byte[] writeBookToByteArray(Book book) throws IOException {
    EpubWriter epubWriter = new EpubWriter();
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    epubWriter.write(book, out);
    return out.toByteArray();
  }
}
