/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Originally from epub4j (https://github.com/documentnode/epub4j)
 * Copyright (C) Paul Siegmund and epub4j contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.grimmory.epub4j.domain;

import java.io.Serial;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.namespace.QName;
import org.grimmory.epub4j.util.StringUtil;

/**
 * A Book's collection of Metadata. In the future it should contain all Dublin Core attributes, for
 * now it contains a set of often-used ones.
 *
 * @author paul
 */
public class Metadata implements Serializable {

  @Serial private static final long serialVersionUID = -2437262888962149444L;

  public static final String DEFAULT_LANGUAGE = "en";

  private boolean autoGeneratedId;
  private List<Author> authors = new ArrayList<>();
  private List<Author> contributors = new ArrayList<>();
  private List<Date> dates = new ArrayList<>();
  private String language = DEFAULT_LANGUAGE;
  private Map<QName, String> otherProperties = new HashMap<>();
  private List<String> rights = new ArrayList<>();
  private List<String> titles = new ArrayList<>();
  private List<Identifier> identifiers = new ArrayList<>();
  private List<String> subjects = new ArrayList<>();
  private String format = MediaTypes.EPUB.name();
  private List<String> types = new ArrayList<>();
  private List<String> descriptions = new ArrayList<>();
  private List<String> publishers = new ArrayList<>();
  private Map<String, String> metaAttributes = new HashMap<>();
  private String subtitle;
  private String seriesName;
  private Float seriesNumber;
  private Integer seriesTotal;
  private Integer pageCount;
  private String renditionLayout;
  private String renditionOrientation;
  private String renditionSpread;
  private String mediaDuration;

  public Metadata() {
    identifiers.add(new Identifier());
    autoGeneratedId = true;
  }

  public boolean isAutoGeneratedId() {
    return autoGeneratedId;
  }

  /**
   * Metadata properties not hard-coded like the author, title, etc.
   *
   * @return Metadata properties not hard-coded like the author, title, etc.
   */
  public Map<QName, String> getOtherProperties() {
    return otherProperties;
  }

  public void setOtherProperties(Map<QName, String> otherProperties) {
    this.otherProperties = otherProperties;
  }

  public void addDate(Date date) {
    this.dates.add(date);
  }

  public List<Date> getDates() {
    return dates;
  }

  public void setDates(List<Date> dates) {
    this.dates = dates;
  }

  public void addAuthor(Author author) {
    authors.add(author);
  }

  public List<Author> getAuthors() {
    return authors;
  }

  public void setAuthors(List<Author> authors) {
    this.authors = authors;
  }

  public void addContributor(Author contributor) {
    contributors.add(contributor);
  }

  public List<Author> getContributors() {
    return contributors;
  }

  public void setContributors(List<Author> contributors) {
    this.contributors = contributors;
  }

  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public List<String> getSubjects() {
    return subjects;
  }

  public void setSubjects(List<String> subjects) {
    this.subjects = subjects;
  }

  public void setRights(List<String> rights) {
    this.rights = rights;
  }

  public List<String> getRights() {
    return rights;
  }

  /**
   * Gets the first non-blank title of the book. Will return "" if no title found.
   *
   * @return the first non-blank title of the book.
   */
  public String getFirstTitle() {
    if (titles == null || titles.isEmpty()) {
      return "";
    }
    for (String title : titles) {
      if (StringUtil.isNotBlank(title)) {
        return title;
      }
    }
    return "";
  }

  public void addTitle(String title) {
    this.titles.add(title);
  }

  public void setTitles(List<String> titles) {
    this.titles = titles;
  }

  public List<String> getTitles() {
    return titles;
  }

  public void addPublisher(String publisher) {
    this.publishers.add(publisher);
  }

  public void setPublishers(List<String> publishers) {
    this.publishers = publishers;
  }

  public List<String> getPublishers() {
    return publishers;
  }

  public void addDescription(String description) {
    this.descriptions.add(description);
  }

  public void setDescriptions(List<String> descriptions) {
    this.descriptions = descriptions;
  }

  public List<String> getDescriptions() {
    return descriptions;
  }

  public void addIdentifier(Identifier identifier) {
    if (autoGeneratedId && (!(identifiers.isEmpty()))) {
      identifiers.set(0, identifier);
    } else {
      identifiers.add(identifier);
    }
    autoGeneratedId = false;
  }

  public void setIdentifiers(List<Identifier> identifiers) {
    this.identifiers = identifiers;
    autoGeneratedId = false;
  }

  public List<Identifier> getIdentifiers() {
    return identifiers;
  }

  public void setFormat(String format) {
    this.format = format;
  }

  public String getFormat() {
    return format;
  }

  public String addType(String type) {
    this.types.add(type);
    return type;
  }

  public List<String> getTypes() {
    return types;
  }

  public void setTypes(List<String> types) {
    this.types = types;
  }

  public String getMetaAttribute(String name) {
    return metaAttributes.get(name);
  }

  public void setMetaAttributes(Map<String, String> metaAttributes) {
    this.metaAttributes = metaAttributes;
  }

  public String getSubtitle() {
    return subtitle;
  }

  public void setSubtitle(String subtitle) {
    this.subtitle = subtitle;
  }

  public String getSeriesName() {
    return seriesName;
  }

  public void setSeriesName(String seriesName) {
    this.seriesName = seriesName;
  }

  public Float getSeriesNumber() {
    return seriesNumber;
  }

  public void setSeriesNumber(Float seriesNumber) {
    this.seriesNumber = seriesNumber;
  }

  public Integer getSeriesTotal() {
    return seriesTotal;
  }

  public void setSeriesTotal(Integer seriesTotal) {
    this.seriesTotal = seriesTotal;
  }

  public Integer getPageCount() {
    return pageCount;
  }

  public void setPageCount(Integer pageCount) {
    this.pageCount = pageCount;
  }

  public String getRenditionLayout() {
    return renditionLayout;
  }

  public void setRenditionLayout(String renditionLayout) {
    this.renditionLayout = renditionLayout;
  }

  public String getRenditionOrientation() {
    return renditionOrientation;
  }

  public void setRenditionOrientation(String renditionOrientation) {
    this.renditionOrientation = renditionOrientation;
  }

  public String getRenditionSpread() {
    return renditionSpread;
  }

  public void setRenditionSpread(String renditionSpread) {
    this.renditionSpread = renditionSpread;
  }

  public String getMediaDuration() {
    return mediaDuration;
  }

  public void setMediaDuration(String mediaDuration) {
    this.mediaDuration = mediaDuration;
  }

  public boolean isFixedLayout() {
    return "pre-paginated".equals(renditionLayout);
  }
}
