// Generated by jextract

package org.grimmory.epub4j.native_parsing;

import java.lang.invoke.*;
import java.lang.foreign.*;

public class EpubNativeHeaders extends EpubNativeHeaders$shared {

    // Ensure native library is loaded before any symbol lookup
    static {
        // Force PanamaConstants to initialize first (loads native library)
        try {
            Class.forName("org.grimmory.epub4j.native_parsing.PanamaConstants");
        } catch (ClassNotFoundException e) {
            throw new RuntimeException("Failed to load PanamaConstants", e);
        }
    }

    EpubNativeHeaders() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());


    private static class epub_native_string_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_string_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void epub_native_string_free(const char *str)
     * }
     */
    public static FunctionDescriptor epub_native_string_free$descriptor() {
        return epub_native_string_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void epub_native_string_free(const char *str)
     * }
     */
    public static MethodHandle epub_native_string_free$handle() {
        return epub_native_string_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void epub_native_string_free(const char *str)
     * }
     */
    public static MemorySegment epub_native_string_free$address() {
        return epub_native_string_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void epub_native_string_free(const char *str)
     * }
     */
    public static void epub_native_string_free(MemorySegment str) {
        var mh$ = epub_native_string_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_string_free", str);
            }
            mh$.invokeExact(str);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_package_parse {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_package_parse");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_parse(const char *xml_content, size_t xml_length, EpubNativePackageDocument **out_doc)
     * }
     */
    public static FunctionDescriptor epub_native_package_parse$descriptor() {
        return epub_native_package_parse.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_parse(const char *xml_content, size_t xml_length, EpubNativePackageDocument **out_doc)
     * }
     */
    public static MethodHandle epub_native_package_parse$handle() {
        return epub_native_package_parse.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_parse(const char *xml_content, size_t xml_length, EpubNativePackageDocument **out_doc)
     * }
     */
    public static MemorySegment epub_native_package_parse$address() {
        return epub_native_package_parse.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_parse(const char *xml_content, size_t xml_length, EpubNativePackageDocument **out_doc)
     * }
     */
    public static int epub_native_package_parse(MemorySegment xml_content, long xml_length, MemorySegment out_doc) {
        var mh$ = epub_native_package_parse.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_package_parse", xml_content, xml_length, out_doc);
            }
            return (int)mh$.invokeExact(xml_content, xml_length, out_doc);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_package_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_package_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void epub_native_package_free(EpubNativePackageDocument *doc)
     * }
     */
    public static FunctionDescriptor epub_native_package_free$descriptor() {
        return epub_native_package_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void epub_native_package_free(EpubNativePackageDocument *doc)
     * }
     */
    public static MethodHandle epub_native_package_free$handle() {
        return epub_native_package_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void epub_native_package_free(EpubNativePackageDocument *doc)
     * }
     */
    public static MemorySegment epub_native_package_free$address() {
        return epub_native_package_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void epub_native_package_free(EpubNativePackageDocument *doc)
     * }
     */
    public static void epub_native_package_free(MemorySegment doc) {
        var mh$ = epub_native_package_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_package_free", doc);
            }
            mh$.invokeExact(doc);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_package_get_id {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_package_get_id");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *epub_native_package_get_id(EpubNativePackageDocument *doc)
     * }
     */
    public static FunctionDescriptor epub_native_package_get_id$descriptor() {
        return epub_native_package_get_id.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *epub_native_package_get_id(EpubNativePackageDocument *doc)
     * }
     */
    public static MethodHandle epub_native_package_get_id$handle() {
        return epub_native_package_get_id.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *epub_native_package_get_id(EpubNativePackageDocument *doc)
     * }
     */
    public static MemorySegment epub_native_package_get_id$address() {
        return epub_native_package_get_id.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *epub_native_package_get_id(EpubNativePackageDocument *doc)
     * }
     */
    public static MemorySegment epub_native_package_get_id(MemorySegment doc) {
        var mh$ = epub_native_package_get_id.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_package_get_id", doc);
            }
            return (MemorySegment)mh$.invokeExact(doc);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_package_get_manifest_item {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_package_get_manifest_item");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_manifest_item(EpubNativePackageDocument *doc, const char *item_id, const char **out_href, const char **out_media_type)
     * }
     */
    public static FunctionDescriptor epub_native_package_get_manifest_item$descriptor() {
        return epub_native_package_get_manifest_item.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_manifest_item(EpubNativePackageDocument *doc, const char *item_id, const char **out_href, const char **out_media_type)
     * }
     */
    public static MethodHandle epub_native_package_get_manifest_item$handle() {
        return epub_native_package_get_manifest_item.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_manifest_item(EpubNativePackageDocument *doc, const char *item_id, const char **out_href, const char **out_media_type)
     * }
     */
    public static MemorySegment epub_native_package_get_manifest_item$address() {
        return epub_native_package_get_manifest_item.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_manifest_item(EpubNativePackageDocument *doc, const char *item_id, const char **out_href, const char **out_media_type)
     * }
     */
    public static int epub_native_package_get_manifest_item(MemorySegment doc, MemorySegment item_id, MemorySegment out_href, MemorySegment out_media_type) {
        var mh$ = epub_native_package_get_manifest_item.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_package_get_manifest_item", doc, item_id, out_href, out_media_type);
            }
            return (int)mh$.invokeExact(doc, item_id, out_href, out_media_type);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_package_get_spine_items {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_package_get_spine_items");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_spine_items(EpubNativePackageDocument *doc, const char ***out_ids, size_t *out_count)
     * }
     */
    public static FunctionDescriptor epub_native_package_get_spine_items$descriptor() {
        return epub_native_package_get_spine_items.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_spine_items(EpubNativePackageDocument *doc, const char ***out_ids, size_t *out_count)
     * }
     */
    public static MethodHandle epub_native_package_get_spine_items$handle() {
        return epub_native_package_get_spine_items.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_spine_items(EpubNativePackageDocument *doc, const char ***out_ids, size_t *out_count)
     * }
     */
    public static MemorySegment epub_native_package_get_spine_items$address() {
        return epub_native_package_get_spine_items.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_spine_items(EpubNativePackageDocument *doc, const char ***out_ids, size_t *out_count)
     * }
     */
    public static int epub_native_package_get_spine_items(MemorySegment doc, MemorySegment out_ids, MemorySegment out_count) {
        var mh$ = epub_native_package_get_spine_items.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_package_get_spine_items", doc, out_ids, out_count);
            }
            return (int)mh$.invokeExact(doc, out_ids, out_count);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_package_free_spine_items {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_package_free_spine_items");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void epub_native_package_free_spine_items(const char **ids, size_t count)
     * }
     */
    public static FunctionDescriptor epub_native_package_free_spine_items$descriptor() {
        return epub_native_package_free_spine_items.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void epub_native_package_free_spine_items(const char **ids, size_t count)
     * }
     */
    public static MethodHandle epub_native_package_free_spine_items$handle() {
        return epub_native_package_free_spine_items.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void epub_native_package_free_spine_items(const char **ids, size_t count)
     * }
     */
    public static MemorySegment epub_native_package_free_spine_items$address() {
        return epub_native_package_free_spine_items.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void epub_native_package_free_spine_items(const char **ids, size_t count)
     * }
     */
    public static void epub_native_package_free_spine_items(MemorySegment ids, long count) {
        var mh$ = epub_native_package_free_spine_items.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_package_free_spine_items", ids, count);
            }
            mh$.invokeExact(ids, count);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_package_get_all_manifest_items {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_package_get_all_manifest_items");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_all_manifest_items(EpubNativePackageDocument *doc, const char ***out_ids, size_t *out_count)
     * }
     */
    public static FunctionDescriptor epub_native_package_get_all_manifest_items$descriptor() {
        return epub_native_package_get_all_manifest_items.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_all_manifest_items(EpubNativePackageDocument *doc, const char ***out_ids, size_t *out_count)
     * }
     */
    public static MethodHandle epub_native_package_get_all_manifest_items$handle() {
        return epub_native_package_get_all_manifest_items.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_all_manifest_items(EpubNativePackageDocument *doc, const char ***out_ids, size_t *out_count)
     * }
     */
    public static MemorySegment epub_native_package_get_all_manifest_items$address() {
        return epub_native_package_get_all_manifest_items.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_all_manifest_items(EpubNativePackageDocument *doc, const char ***out_ids, size_t *out_count)
     * }
     */
    public static int epub_native_package_get_all_manifest_items(MemorySegment doc, MemorySegment out_ids, MemorySegment out_count) {
        var mh$ = epub_native_package_get_all_manifest_items.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_package_get_all_manifest_items", doc, out_ids, out_count);
            }
            return (int)mh$.invokeExact(doc, out_ids, out_count);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_package_get_cover {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_package_get_cover");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_cover(EpubNativePackageDocument *doc, const char **out_cover_href)
     * }
     */
    public static FunctionDescriptor epub_native_package_get_cover$descriptor() {
        return epub_native_package_get_cover.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_cover(EpubNativePackageDocument *doc, const char **out_cover_href)
     * }
     */
    public static MethodHandle epub_native_package_get_cover$handle() {
        return epub_native_package_get_cover.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_cover(EpubNativePackageDocument *doc, const char **out_cover_href)
     * }
     */
    public static MemorySegment epub_native_package_get_cover$address() {
        return epub_native_package_get_cover.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_cover(EpubNativePackageDocument *doc, const char **out_cover_href)
     * }
     */
    public static int epub_native_package_get_cover(MemorySegment doc, MemorySegment out_cover_href) {
        var mh$ = epub_native_package_get_cover.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_package_get_cover", doc, out_cover_href);
            }
            return (int)mh$.invokeExact(doc, out_cover_href);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_package_get_metadata {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_package_get_metadata");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_metadata(EpubNativePackageDocument *doc, const char *metadata_name, const char **out_value)
     * }
     */
    public static FunctionDescriptor epub_native_package_get_metadata$descriptor() {
        return epub_native_package_get_metadata.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_metadata(EpubNativePackageDocument *doc, const char *metadata_name, const char **out_value)
     * }
     */
    public static MethodHandle epub_native_package_get_metadata$handle() {
        return epub_native_package_get_metadata.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_metadata(EpubNativePackageDocument *doc, const char *metadata_name, const char **out_value)
     * }
     */
    public static MemorySegment epub_native_package_get_metadata$address() {
        return epub_native_package_get_metadata.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_package_get_metadata(EpubNativePackageDocument *doc, const char *metadata_name, const char **out_value)
     * }
     */
    public static int epub_native_package_get_metadata(MemorySegment doc, MemorySegment metadata_name, MemorySegment out_value) {
        var mh$ = epub_native_package_get_metadata.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_package_get_metadata", doc, metadata_name, out_value);
            }
            return (int)mh$.invokeExact(doc, metadata_name, out_value);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_ncx_parse {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_ncx_parse");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_parse(const char *xml_content, size_t xml_length, EpubNativeNCXDocument **out_doc)
     * }
     */
    public static FunctionDescriptor epub_native_ncx_parse$descriptor() {
        return epub_native_ncx_parse.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_parse(const char *xml_content, size_t xml_length, EpubNativeNCXDocument **out_doc)
     * }
     */
    public static MethodHandle epub_native_ncx_parse$handle() {
        return epub_native_ncx_parse.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_parse(const char *xml_content, size_t xml_length, EpubNativeNCXDocument **out_doc)
     * }
     */
    public static MemorySegment epub_native_ncx_parse$address() {
        return epub_native_ncx_parse.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_parse(const char *xml_content, size_t xml_length, EpubNativeNCXDocument **out_doc)
     * }
     */
    public static int epub_native_ncx_parse(MemorySegment xml_content, long xml_length, MemorySegment out_doc) {
        var mh$ = epub_native_ncx_parse.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_ncx_parse", xml_content, xml_length, out_doc);
            }
            return (int)mh$.invokeExact(xml_content, xml_length, out_doc);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_ncx_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_ncx_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void epub_native_ncx_free(EpubNativeNCXDocument *doc)
     * }
     */
    public static FunctionDescriptor epub_native_ncx_free$descriptor() {
        return epub_native_ncx_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void epub_native_ncx_free(EpubNativeNCXDocument *doc)
     * }
     */
    public static MethodHandle epub_native_ncx_free$handle() {
        return epub_native_ncx_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void epub_native_ncx_free(EpubNativeNCXDocument *doc)
     * }
     */
    public static MemorySegment epub_native_ncx_free$address() {
        return epub_native_ncx_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void epub_native_ncx_free(EpubNativeNCXDocument *doc)
     * }
     */
    public static void epub_native_ncx_free(MemorySegment doc) {
        var mh$ = epub_native_ncx_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_ncx_free", doc);
            }
            mh$.invokeExact(doc);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_ncx_get_toc_references {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_ncx_get_toc_references");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_get_toc_references(EpubNativeNCXDocument *doc, EpubNativeTOCReference **out_refs, size_t *out_count)
     * }
     */
    public static FunctionDescriptor epub_native_ncx_get_toc_references$descriptor() {
        return epub_native_ncx_get_toc_references.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_get_toc_references(EpubNativeNCXDocument *doc, EpubNativeTOCReference **out_refs, size_t *out_count)
     * }
     */
    public static MethodHandle epub_native_ncx_get_toc_references$handle() {
        return epub_native_ncx_get_toc_references.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_get_toc_references(EpubNativeNCXDocument *doc, EpubNativeTOCReference **out_refs, size_t *out_count)
     * }
     */
    public static MemorySegment epub_native_ncx_get_toc_references$address() {
        return epub_native_ncx_get_toc_references.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_get_toc_references(EpubNativeNCXDocument *doc, EpubNativeTOCReference **out_refs, size_t *out_count)
     * }
     */
    public static int epub_native_ncx_get_toc_references(MemorySegment doc, MemorySegment out_refs, MemorySegment out_count) {
        var mh$ = epub_native_ncx_get_toc_references.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_ncx_get_toc_references", doc, out_refs, out_count);
            }
            return (int)mh$.invokeExact(doc, out_refs, out_count);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_ncx_free_toc_references {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_ncx_free_toc_references");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void epub_native_ncx_free_toc_references(EpubNativeTOCReference *refs, size_t count)
     * }
     */
    public static FunctionDescriptor epub_native_ncx_free_toc_references$descriptor() {
        return epub_native_ncx_free_toc_references.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void epub_native_ncx_free_toc_references(EpubNativeTOCReference *refs, size_t count)
     * }
     */
    public static MethodHandle epub_native_ncx_free_toc_references$handle() {
        return epub_native_ncx_free_toc_references.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void epub_native_ncx_free_toc_references(EpubNativeTOCReference *refs, size_t count)
     * }
     */
    public static MemorySegment epub_native_ncx_free_toc_references$address() {
        return epub_native_ncx_free_toc_references.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void epub_native_ncx_free_toc_references(EpubNativeTOCReference *refs, size_t count)
     * }
     */
    public static void epub_native_ncx_free_toc_references(MemorySegment refs, long count) {
        var mh$ = epub_native_ncx_free_toc_references.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_ncx_free_toc_references", refs, count);
            }
            mh$.invokeExact(refs, count);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_ncx_write {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_ncx_write");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_write(const char **identifiers, size_t identifier_count, const char *title, const char **authors, size_t author_count, const EpubNativeTOCReference *toc_refs, size_t toc_count, char **out_xml)
     * }
     */
    public static FunctionDescriptor epub_native_ncx_write$descriptor() {
        return epub_native_ncx_write.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_write(const char **identifiers, size_t identifier_count, const char *title, const char **authors, size_t author_count, const EpubNativeTOCReference *toc_refs, size_t toc_count, char **out_xml)
     * }
     */
    public static MethodHandle epub_native_ncx_write$handle() {
        return epub_native_ncx_write.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_write(const char **identifiers, size_t identifier_count, const char *title, const char **authors, size_t author_count, const EpubNativeTOCReference *toc_refs, size_t toc_count, char **out_xml)
     * }
     */
    public static MemorySegment epub_native_ncx_write$address() {
        return epub_native_ncx_write.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_ncx_write(const char **identifiers, size_t identifier_count, const char *title, const char **authors, size_t author_count, const EpubNativeTOCReference *toc_refs, size_t toc_count, char **out_xml)
     * }
     */
    public static int epub_native_ncx_write(MemorySegment identifiers, long identifier_count, MemorySegment title, MemorySegment authors, long author_count, MemorySegment toc_refs, long toc_count, MemorySegment out_xml) {
        var mh$ = epub_native_ncx_write.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_ncx_write", identifiers, identifier_count, title, authors, author_count, toc_refs, toc_count, out_xml);
            }
            return (int)mh$.invokeExact(identifiers, identifier_count, title, authors, author_count, toc_refs, toc_count, out_xml);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_nav_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_nav_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_nav_create(const char *title, const EpubNativeTOCReference *toc_refs, size_t toc_count, char **out_xhtml)
     * }
     */
    public static FunctionDescriptor epub_native_nav_create$descriptor() {
        return epub_native_nav_create.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_nav_create(const char *title, const EpubNativeTOCReference *toc_refs, size_t toc_count, char **out_xhtml)
     * }
     */
    public static MethodHandle epub_native_nav_create$handle() {
        return epub_native_nav_create.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_nav_create(const char *title, const EpubNativeTOCReference *toc_refs, size_t toc_count, char **out_xhtml)
     * }
     */
    public static MemorySegment epub_native_nav_create$address() {
        return epub_native_nav_create.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_nav_create(const char *title, const EpubNativeTOCReference *toc_refs, size_t toc_count, char **out_xhtml)
     * }
     */
    public static int epub_native_nav_create(MemorySegment title, MemorySegment toc_refs, long toc_count, MemorySegment out_xhtml) {
        var mh$ = epub_native_nav_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_nav_create", title, toc_refs, toc_count, out_xhtml);
            }
            return (int)mh$.invokeExact(title, toc_refs, toc_count, out_xhtml);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_html_cleaner_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_html_cleaner_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_html_cleaner_create(EpubNativeHtmlCleaner **out_cleaner)
     * }
     */
    public static FunctionDescriptor epub_native_html_cleaner_create$descriptor() {
        return epub_native_html_cleaner_create.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_html_cleaner_create(EpubNativeHtmlCleaner **out_cleaner)
     * }
     */
    public static MethodHandle epub_native_html_cleaner_create$handle() {
        return epub_native_html_cleaner_create.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_html_cleaner_create(EpubNativeHtmlCleaner **out_cleaner)
     * }
     */
    public static MemorySegment epub_native_html_cleaner_create$address() {
        return epub_native_html_cleaner_create.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_html_cleaner_create(EpubNativeHtmlCleaner **out_cleaner)
     * }
     */
    public static int epub_native_html_cleaner_create(MemorySegment out_cleaner) {
        var mh$ = epub_native_html_cleaner_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_html_cleaner_create", out_cleaner);
            }
            return (int)mh$.invokeExact(out_cleaner);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_html_cleaner_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_html_cleaner_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void epub_native_html_cleaner_free(EpubNativeHtmlCleaner *cleaner)
     * }
     */
    public static FunctionDescriptor epub_native_html_cleaner_free$descriptor() {
        return epub_native_html_cleaner_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void epub_native_html_cleaner_free(EpubNativeHtmlCleaner *cleaner)
     * }
     */
    public static MethodHandle epub_native_html_cleaner_free$handle() {
        return epub_native_html_cleaner_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void epub_native_html_cleaner_free(EpubNativeHtmlCleaner *cleaner)
     * }
     */
    public static MemorySegment epub_native_html_cleaner_free$address() {
        return epub_native_html_cleaner_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void epub_native_html_cleaner_free(EpubNativeHtmlCleaner *cleaner)
     * }
     */
    public static void epub_native_html_cleaner_free(MemorySegment cleaner) {
        var mh$ = epub_native_html_cleaner_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_html_cleaner_free", cleaner);
            }
            mh$.invokeExact(cleaner);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_html_clean {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_html_clean");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_html_clean(EpubNativeHtmlCleaner *cleaner, const char *html_content, size_t html_length, const char *output_encoding, char **out_xhtml, size_t *out_length)
     * }
     */
    public static FunctionDescriptor epub_native_html_clean$descriptor() {
        return epub_native_html_clean.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_html_clean(EpubNativeHtmlCleaner *cleaner, const char *html_content, size_t html_length, const char *output_encoding, char **out_xhtml, size_t *out_length)
     * }
     */
    public static MethodHandle epub_native_html_clean$handle() {
        return epub_native_html_clean.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * EpubNativeError epub_native_html_clean(EpubNativeHtmlCleaner *cleaner, const char *html_content, size_t html_length, const char *output_encoding, char **out_xhtml, size_t *out_length)
     * }
     */
    public static MemorySegment epub_native_html_clean$address() {
        return epub_native_html_clean.ADDR;
    }

    /**
     * {@snippet lang=c :
     * EpubNativeError epub_native_html_clean(EpubNativeHtmlCleaner *cleaner, const char *html_content, size_t html_length, const char *output_encoding, char **out_xhtml, size_t *out_length)
     * }
     */
    public static int epub_native_html_clean(MemorySegment cleaner, MemorySegment html_content, long html_length, MemorySegment output_encoding, MemorySegment out_xhtml, MemorySegment out_length) {
        var mh$ = epub_native_html_clean.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_html_clean", cleaner, html_content, html_length, output_encoding, out_xhtml, out_length);
            }
            return (int)mh$.invokeExact(cleaner, html_content, html_length, output_encoding, out_xhtml, out_length);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_get_version {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_POINTER    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_get_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *epub_native_get_version()
     * }
     */
    public static FunctionDescriptor epub_native_get_version$descriptor() {
        return epub_native_get_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *epub_native_get_version()
     * }
     */
    public static MethodHandle epub_native_get_version$handle() {
        return epub_native_get_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *epub_native_get_version()
     * }
     */
    public static MemorySegment epub_native_get_version$address() {
        return epub_native_get_version.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *epub_native_get_version()
     * }
     */
    public static MemorySegment epub_native_get_version() {
        var mh$ = epub_native_get_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_get_version");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_get_last_error {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_POINTER    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_get_last_error");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *epub_native_get_last_error()
     * }
     */
    public static FunctionDescriptor epub_native_get_last_error$descriptor() {
        return epub_native_get_last_error.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *epub_native_get_last_error()
     * }
     */
    public static MethodHandle epub_native_get_last_error$handle() {
        return epub_native_get_last_error.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *epub_native_get_last_error()
     * }
     */
    public static MemorySegment epub_native_get_last_error$address() {
        return epub_native_get_last_error.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *epub_native_get_last_error()
     * }
     */
    public static MemorySegment epub_native_get_last_error() {
        var mh$ = epub_native_get_last_error.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_get_last_error");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_encoding_detector_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_encoding_detector_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static FunctionDescriptor epub_native_encoding_detector_create$descriptor() {
        return epub_native_encoding_detector_create.DESC;
    }

    public static MethodHandle epub_native_encoding_detector_create$handle() {
        return epub_native_encoding_detector_create.HANDLE;
    }

    public static MemorySegment epub_native_encoding_detector_create$address() {
        return epub_native_encoding_detector_create.ADDR;
    }

    public static int epub_native_encoding_detector_create(MemorySegment out_detector) {
        var mh$ = epub_native_encoding_detector_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_encoding_detector_create", out_detector);
            }
            return (int)mh$.invokeExact(out_detector);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_encoding_detector_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_encoding_detector_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static FunctionDescriptor epub_native_encoding_detector_free$descriptor() {
        return epub_native_encoding_detector_free.DESC;
    }

    public static MethodHandle epub_native_encoding_detector_free$handle() {
        return epub_native_encoding_detector_free.HANDLE;
    }

    public static MemorySegment epub_native_encoding_detector_free$address() {
        return epub_native_encoding_detector_free.ADDR;
    }

    public static void epub_native_encoding_detector_free(MemorySegment detector) {
        var mh$ = epub_native_encoding_detector_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_encoding_detector_free", detector);
            }
            mh$.invokeExact(detector);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_detect_encoding {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_detect_encoding");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static FunctionDescriptor epub_native_detect_encoding$descriptor() {
        return epub_native_detect_encoding.DESC;
    }

    public static MethodHandle epub_native_detect_encoding$handle() {
        return epub_native_detect_encoding.HANDLE;
    }

    public static MemorySegment epub_native_detect_encoding$address() {
        return epub_native_detect_encoding.ADDR;
    }

    public static int epub_native_detect_encoding(MemorySegment detector, MemorySegment data, long data_length, MemorySegment out_encoding, MemorySegment out_confidence) {
        var mh$ = epub_native_detect_encoding.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_detect_encoding", detector, data, data_length, out_encoding, out_confidence);
            }
            return (int)mh$.invokeExact(detector, data, data_length, out_encoding, out_confidence);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_convert_to_utf8 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_convert_to_utf8");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static FunctionDescriptor epub_native_convert_to_utf8$descriptor() {
        return epub_native_convert_to_utf8.DESC;
    }

    public static MethodHandle epub_native_convert_to_utf8$handle() {
        return epub_native_convert_to_utf8.HANDLE;
    }

    public static MemorySegment epub_native_convert_to_utf8$address() {
        return epub_native_convert_to_utf8.ADDR;
    }

    public static int epub_native_convert_to_utf8(MemorySegment source_encoding, MemorySegment source_data, long source_length, MemorySegment out_utf8, MemorySegment out_utf8_length) {
        var mh$ = epub_native_convert_to_utf8.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_convert_to_utf8", source_encoding, source_data, source_length, out_utf8, out_utf8_length);
            }
            return (int)mh$.invokeExact(source_encoding, source_data, source_length, out_utf8, out_utf8_length);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_archive_open {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_archive_open");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static FunctionDescriptor epub_native_archive_open$descriptor() {
        return epub_native_archive_open.DESC;
    }

    public static MethodHandle epub_native_archive_open$handle() {
        return epub_native_archive_open.HANDLE;
    }

    public static MemorySegment epub_native_archive_open$address() {
        return epub_native_archive_open.ADDR;
    }

    public static int epub_native_archive_open(MemorySegment filepath, MemorySegment out_archive) {
        var mh$ = epub_native_archive_open.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_archive_open", filepath, out_archive);
            }
            return (int)mh$.invokeExact(filepath, out_archive);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_archive_open_memory {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_archive_open_memory");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static FunctionDescriptor epub_native_archive_open_memory$descriptor() {
        return epub_native_archive_open_memory.DESC;
    }

    public static MethodHandle epub_native_archive_open_memory$handle() {
        return epub_native_archive_open_memory.HANDLE;
    }

    public static MemorySegment epub_native_archive_open_memory$address() {
        return epub_native_archive_open_memory.ADDR;
    }

    public static int epub_native_archive_open_memory(MemorySegment data, long data_length, MemorySegment out_archive) {
        var mh$ = epub_native_archive_open_memory.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_archive_open_memory", data, data_length, out_archive);
            }
            return (int)mh$.invokeExact(data, data_length, out_archive);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_archive_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_archive_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static FunctionDescriptor epub_native_archive_free$descriptor() {
        return epub_native_archive_free.DESC;
    }

    public static MethodHandle epub_native_archive_free$handle() {
        return epub_native_archive_free.HANDLE;
    }

    public static MemorySegment epub_native_archive_free$address() {
        return epub_native_archive_free.ADDR;
    }

    public static void epub_native_archive_free(MemorySegment archive) {
        var mh$ = epub_native_archive_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_archive_free", archive);
            }
            mh$.invokeExact(archive);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_archive_list_entries {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_archive_list_entries");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static FunctionDescriptor epub_native_archive_list_entries$descriptor() {
        return epub_native_archive_list_entries.DESC;
    }

    public static MethodHandle epub_native_archive_list_entries$handle() {
        return epub_native_archive_list_entries.HANDLE;
    }

    public static MemorySegment epub_native_archive_list_entries$address() {
        return epub_native_archive_list_entries.ADDR;
    }

    public static int epub_native_archive_list_entries(MemorySegment archive, MemorySegment out_entries, MemorySegment out_count) {
        var mh$ = epub_native_archive_list_entries.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_archive_list_entries", archive, out_entries, out_count);
            }
            return (int)mh$.invokeExact(archive, out_entries, out_count);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_archive_free_string_array {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_archive_free_string_array");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static FunctionDescriptor epub_native_archive_free_string_array$descriptor() {
        return epub_native_archive_free_string_array.DESC;
    }

    public static MethodHandle epub_native_archive_free_string_array$handle() {
        return epub_native_archive_free_string_array.HANDLE;
    }

    public static MemorySegment epub_native_archive_free_string_array$address() {
        return epub_native_archive_free_string_array.ADDR;
    }

    public static void epub_native_archive_free_string_array(MemorySegment entries, long count) {
        var mh$ = epub_native_archive_free_string_array.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_archive_free_string_array", entries, count);
            }
            mh$.invokeExact(entries, count);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_archive_read_entry {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_archive_read_entry");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static FunctionDescriptor epub_native_archive_read_entry$descriptor() {
        return epub_native_archive_read_entry.DESC;
    }

    public static MethodHandle epub_native_archive_read_entry$handle() {
        return epub_native_archive_read_entry.HANDLE;
    }

    public static MemorySegment epub_native_archive_read_entry$address() {
        return epub_native_archive_read_entry.ADDR;
    }

    public static int epub_native_archive_read_entry(MemorySegment archive, MemorySegment entry_path, MemorySegment out_data, MemorySegment out_data_length) {
        var mh$ = epub_native_archive_read_entry.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_archive_read_entry", archive, entry_path, out_data, out_data_length);
            }
            return (int)mh$.invokeExact(archive, entry_path, out_data, out_data_length);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class epub_native_archive_entry_exists {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            EpubNativeHeaders.C_INT,
            EpubNativeHeaders.C_POINTER,
            EpubNativeHeaders.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_archive_entry_exists");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static FunctionDescriptor epub_native_archive_entry_exists$descriptor() {
        return epub_native_archive_entry_exists.DESC;
    }

    public static MethodHandle epub_native_archive_entry_exists$handle() {
        return epub_native_archive_entry_exists.HANDLE;
    }

    public static MemorySegment epub_native_archive_entry_exists$address() {
        return epub_native_archive_entry_exists.ADDR;
    }

    public static int epub_native_archive_entry_exists(MemorySegment archive, MemorySegment entry_path) {
        var mh$ = epub_native_archive_entry_exists.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("epub_native_archive_entry_exists", archive, entry_path);
            }
            return (int)mh$.invokeExact(archive, entry_path);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    // ========================================================================
    // Image Processing
    // ========================================================================

    private static class epub_native_image_has_jpeg {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(C_INT);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_image_has_jpeg");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static int epub_native_image_has_jpeg() {
        var mh$ = epub_native_image_has_jpeg.HANDLE;
        try {
            if (TRACE_DOWNCALLS) { traceDowncall("epub_native_image_has_jpeg"); }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) { throw ex;
        } catch (Throwable ex$) { throw new AssertionError("should not reach here", ex$); }
    }

    private static class epub_native_image_has_png {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(C_INT);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_image_has_png");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static int epub_native_image_has_png() {
        var mh$ = epub_native_image_has_png.HANDLE;
        try {
            if (TRACE_DOWNCALLS) { traceDowncall("epub_native_image_has_png"); }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) { throw ex;
        } catch (Throwable ex$) { throw new AssertionError("should not reach here", ex$); }
    }

    private static class epub_native_image_has_webp {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(C_INT);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_image_has_webp");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static int epub_native_image_has_webp() {
        var mh$ = epub_native_image_has_webp.HANDLE;
        try {
            if (TRACE_DOWNCALLS) { traceDowncall("epub_native_image_has_webp"); }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) { throw ex;
        } catch (Throwable ex$) { throw new AssertionError("should not reach here", ex$); }
    }

    private static class epub_native_image_get_dimensions {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            C_INT, C_POINTER, C_LONG_LONG, C_POINTER, C_POINTER, C_POINTER
        );
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_image_get_dimensions");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static int epub_native_image_get_dimensions(MemorySegment data, long data_length, MemorySegment out_width, MemorySegment out_height, MemorySegment out_format) {
        var mh$ = epub_native_image_get_dimensions.HANDLE;
        try {
            if (TRACE_DOWNCALLS) { traceDowncall("epub_native_image_get_dimensions", data, data_length, out_width, out_height, out_format); }
            return (int)mh$.invokeExact(data, data_length, out_width, out_height, out_format);
        } catch (Error | RuntimeException ex) { throw ex;
        } catch (Throwable ex$) { throw new AssertionError("should not reach here", ex$); }
    }

    private static class epub_native_jpeg_optimize {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            C_INT, C_POINTER, C_LONG_LONG, C_POINTER, C_POINTER
        );
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_jpeg_optimize");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static int epub_native_jpeg_optimize(MemorySegment data, long data_length, MemorySegment out_data, MemorySegment out_length) {
        var mh$ = epub_native_jpeg_optimize.HANDLE;
        try {
            if (TRACE_DOWNCALLS) { traceDowncall("epub_native_jpeg_optimize", data, data_length, out_data, out_length); }
            return (int)mh$.invokeExact(data, data_length, out_data, out_length);
        } catch (Error | RuntimeException ex) { throw ex;
        } catch (Throwable ex$) { throw new AssertionError("should not reach here", ex$); }
    }

    private static class epub_native_jpeg_compress {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            C_INT, C_POINTER, C_LONG_LONG, C_INT, C_INT, C_POINTER, C_POINTER
        );
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_jpeg_compress");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static int epub_native_jpeg_compress(MemorySegment data, long data_length, int quality, int progressive, MemorySegment out_data, MemorySegment out_length) {
        var mh$ = epub_native_jpeg_compress.HANDLE;
        try {
            if (TRACE_DOWNCALLS) { traceDowncall("epub_native_jpeg_compress", data, data_length, quality, progressive, out_data, out_length); }
            return (int)mh$.invokeExact(data, data_length, quality, progressive, out_data, out_length);
        } catch (Error | RuntimeException ex) { throw ex;
        } catch (Throwable ex$) { throw new AssertionError("should not reach here", ex$); }
    }

    private static class epub_native_png_optimize {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            C_INT, C_POINTER, C_LONG_LONG, C_INT, C_POINTER, C_POINTER
        );
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_png_optimize");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static int epub_native_png_optimize(MemorySegment data, long data_length, int strip_ancillary, MemorySegment out_data, MemorySegment out_length) {
        var mh$ = epub_native_png_optimize.HANDLE;
        try {
            if (TRACE_DOWNCALLS) { traceDowncall("epub_native_png_optimize", data, data_length, strip_ancillary, out_data, out_length); }
            return (int)mh$.invokeExact(data, data_length, strip_ancillary, out_data, out_length);
        } catch (Error | RuntimeException ex) { throw ex;
        } catch (Throwable ex$) { throw new AssertionError("should not reach here", ex$); }
    }

    private static class epub_native_webp_encode {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            C_INT, C_POINTER, C_INT, C_INT, C_INT, C_INT, C_POINTER, C_POINTER
        );
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_webp_encode");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static int epub_native_webp_encode(MemorySegment rgba_pixels, int width, int height, int stride, int quality, MemorySegment out_data, MemorySegment out_length) {
        var mh$ = epub_native_webp_encode.HANDLE;
        try {
            if (TRACE_DOWNCALLS) { traceDowncall("epub_native_webp_encode", rgba_pixels, width, height, stride, quality, out_data, out_length); }
            return (int)mh$.invokeExact(rgba_pixels, width, height, stride, quality, out_data, out_length);
        } catch (Error | RuntimeException ex) { throw ex;
        } catch (Throwable ex$) { throw new AssertionError("should not reach here", ex$); }
    }

    private static class epub_native_image_resize {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            C_INT, C_POINTER, C_LONG_LONG, C_INT, C_INT, C_INT, C_INT, C_POINTER, C_POINTER
        );
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_image_resize");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static int epub_native_image_resize(MemorySegment data, long data_length, int target_width, int target_height, int output_format, int quality, MemorySegment out_data, MemorySegment out_length) {
        var mh$ = epub_native_image_resize.HANDLE;
        try {
            if (TRACE_DOWNCALLS) { traceDowncall("epub_native_image_resize", data, data_length, target_width, target_height, output_format, quality, out_data, out_length); }
            return (int)mh$.invokeExact(data, data_length, target_width, target_height, output_format, quality, out_data, out_length);
        } catch (Error | RuntimeException ex) { throw ex;
        } catch (Throwable ex$) { throw new AssertionError("should not reach here", ex$); }
    }

    private static class epub_native_image_data_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(C_POINTER);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("epub_native_image_data_free");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static void epub_native_image_data_free(MemorySegment data) {
        var mh$ = epub_native_image_data_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) { traceDowncall("epub_native_image_data_free", data); }
            mh$.invokeExact(data);
        } catch (Error | RuntimeException ex) { throw ex;
        } catch (Throwable ex$) { throw new AssertionError("should not reach here", ex$); }
    }
}
