// Generated by jextract

package org.grimmory.epub4j.native_parsing;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     const char *title;
 *     const char *href;
 *     int play_order;
 *     int has_children;
 * }
 * }
 */
public class EpubNativeTOCReference {

    EpubNativeTOCReference() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        EpubNativeHeaders.C_POINTER.withName("title"),
        EpubNativeHeaders.C_POINTER.withName("href"),
        EpubNativeHeaders.C_INT.withName("play_order"),
        EpubNativeHeaders.C_INT.withName("has_children")
    ).withName("$anon$182:9");

    /**
     * The layout of this struct
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout title$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("title"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *title
     * }
     */
    public static AddressLayout title$layout() {
        return title$LAYOUT;
    }

    private static final long title$OFFSET = $LAYOUT.byteOffset(groupElement("title"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *title
     * }
     */
    public static long title$offset() {
        return title$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *title
     * }
     */
    public static MemorySegment title(MemorySegment struct) {
        return struct.get(title$LAYOUT, title$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *title
     * }
     */
    public static void title(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(title$LAYOUT, title$OFFSET, fieldValue);
    }

    private static final AddressLayout href$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("href"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *href
     * }
     */
    public static AddressLayout href$layout() {
        return href$LAYOUT;
    }

    private static final long href$OFFSET = $LAYOUT.byteOffset(groupElement("href"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *href
     * }
     */
    public static long href$offset() {
        return href$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *href
     * }
     */
    public static MemorySegment href(MemorySegment struct) {
        return struct.get(href$LAYOUT, href$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *href
     * }
     */
    public static void href(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(href$LAYOUT, href$OFFSET, fieldValue);
    }

    private static final OfInt play_order$LAYOUT = (OfInt)$LAYOUT.select(groupElement("play_order"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int play_order
     * }
     */
    public static OfInt play_order$layout() {
        return play_order$LAYOUT;
    }

    private static final long play_order$OFFSET = $LAYOUT.byteOffset(groupElement("play_order"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int play_order
     * }
     */
    public static long play_order$offset() {
        return play_order$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int play_order
     * }
     */
    public static int play_order(MemorySegment struct) {
        return struct.get(play_order$LAYOUT, play_order$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int play_order
     * }
     */
    public static void play_order(MemorySegment struct, int fieldValue) {
        struct.set(play_order$LAYOUT, play_order$OFFSET, fieldValue);
    }

    private static final OfInt has_children$LAYOUT = (OfInt)$LAYOUT.select(groupElement("has_children"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int has_children
     * }
     */
    public static OfInt has_children$layout() {
        return has_children$LAYOUT;
    }

    private static final long has_children$OFFSET = $LAYOUT.byteOffset(groupElement("has_children"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int has_children
     * }
     */
    public static long has_children$offset() {
        return has_children$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int has_children
     * }
     */
    public static int has_children(MemorySegment struct) {
        return struct.get(has_children$LAYOUT, has_children$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int has_children
     * }
     */
    public static void has_children(MemorySegment struct, int fieldValue) {
        struct.set(has_children$LAYOUT, has_children$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
